lists = List.create([
  {list_name: "Costco", description: "Almond Milk", done: true},
  {list_name: "Costco", description: "Almonds", done: true},
  {list_name: "Costco", description: "Bread", done: true},
  {list_name: "Costco", description: "Cashews", done: true},
  {list_name: "Costco", description: "Cat Food", done: true},
  {list_name: "Costco", description: "Cat Litter", done: true},
  {list_name: "Costco", description: "Cherries", done: true},
  {list_name: "Costco", description: "Craisins", done: true},
  {list_name: "Costco", description: "Dishwasher Pellets", done: true},
  {list_name: "Costco", description: "Emergen-C", done: true},
  {list_name: "Costco", description: "Garbage Bags - 30 gal", done: true},
  {list_name: "Costco", description: "Hemp Seeds", done: true},
  {list_name: "Costco", description: "Kettle Chips", done: true},
  {list_name: "Costco", description: "Laundry Soap", done: true},
  {list_name: "Costco", description: "Mixed Nuts", done: true},
  {list_name: "Costco", description: "Paper Towels", done: true},
  {list_name: "Costco", description: "Peanut Butter", done: true},
  {list_name: "Costco", description: "Pistacios", done: true},
  {list_name: "Costco", description: "Pita Chips", done: true},
  {list_name: "Costco", description: "Q'ia", done: true},
  {list_name: "Costco", description: "Quinoa", done: true},
  {list_name: "Costco", description: "Salsa", done: true},
  {list_name: "Costco", description: "Sparkling Water", done: true},
  {list_name: "Costco", description: "Strawberry Jam", done: true},
  {list_name: "Costco", description: "Sun Dried Tomatoes", done: true},
  {list_name: "Costco", description: "Toilet Paper", done: true},
  {list_name: "Costco", description: "Walnuts", done: true},
  {list_name: "Whole Foods", description: "Black Lentls", done: true},
  {list_name: "Foodland", description: "NA Beer", done: true}
])
